version: "3.9"

services:
  avd-workshops:
    build: .
    image: "avd-workshops:latest"
    container_name: avd-workshops
    restart: always
    command: ['tail', '-f', '/dev/null']

    environment:
      - TZ=America/New_York
      - DEBIAN_FRONTEND=noninteractive
    volumes:
      - ../:/workspace
